name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8474269789fc419e50cf376e9d64ac79d3c3949cbef3a0fdde090f8871a93a61"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
