name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d38a24192cd5632576a208640286ad3a302909f95134bfe8deb0990fd1cc8450"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
