name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1b57c1aed26707cec14d4df1b4d92e973f0260efbcdae859e8afea3824ee190"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
