name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c74d585ecc426d8caedc0d525130de3f92f447f173fb082e28f2fe4d22725c3f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
