name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c9d8bd8ea9541625386d9091d8515e39530361ee9754129699a1ed59c8be7ee"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
