name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd903acb2ba91e6cdd3fe8d4037b71495cc1e879b48f4884ba958a1ba3e487c7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
