name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73a8f904bae0aad3ef2774e4c80ef2cbe8f0c6902eb2340fa00c777f346be97c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
