name = "Jaffa Factory 2 (Replica)"
version = "18/12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99aa200fa47cc5e668834794a5073c85d1a97a7c166cda14249ffbf4ef059f19"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
